import os
import re

tpl_dir = r'c:\WFH\jeremy\12. CvSU_Scheduling_System-Version-2.25_send\CvSU_Scheduling_System-Version-2 - antigravity_2_claude - Copy\templates'
files = [f for f in os.listdir(tpl_dir) if f.endswith('.html')]

print("PAGE | PREFIX OK? | OVERFLOW RISK? (Longest text)")

for f in files:
    path = os.path.join(tpl_dir, f)
    with open(path, 'r', encoding='utf-8') as file:
        content = file.read()
    
    if 'google-sort-toggle' in content:
        # Check if the prefix "Sort by" is literally missing in the toggle button
        has_prefix = False
        longest_text = ""
        max_len = 0
        
        matches = re.finditer(r'<button[^>]*google-sort-toggle[^>]*>(.*?)</button>', content, re.DOTALL)
        for m in matches:
            raw_text = m.group(1).strip()
            if 'Sort by:' in raw_text or 'Sort By:' in raw_text or 'Sort by' in raw_text:
                has_prefix = True
                
            clean_text = re.sub(r'<[^>]+>', ' ', raw_text)
            clean_text = re.sub(r'\{%[^%]+%\}', '', clean_text)
            clean_text = re.sub(r'\{\{[^}]+\}\}', '', clean_text)
            clean_text = ' '.join(clean_text.split())
            
            # The actual text shown might be longer, let's also grab the individual labels from the jinja conditionals
            # like "Sort by: Academic Year (High-Low)"
            
            if len(clean_text) > max_len:
                max_len = len(clean_text)
                longest_text = clean_text

        # Let's also check the individual options inside the python code/jinja to be more accurate
        # because the button text is generated by jinja.
        # So we'll look for google-sort-item too.
        items = re.finditer(r'<a[^>]*google-sort-item[^>]*>(.*?)</a>', content, re.DOTALL)
        for item in items:
            raw_item = item.group(1).strip()
            
            # remove jinja and html
            clean_item = re.sub(r'<[^>]+>', ' ', raw_item)
            clean_item = re.sub(r'\{%[^%]+%\}', '', clean_item)
            clean_item = re.sub(r'\{\{[^}]+\}\}', '', clean_item)
            clean_item = ' '.join(clean_item.split())
            
            if len(clean_item) > max_len:
                max_len = len(clean_item)
                longest_text = clean_item

            if 'Sort by' not in raw_item:
                pass # Usually only button matters, but good to know
                
        overflow_risk = max_len > 22 # e.g. "Sort by: Academic Year (A-Z)" is 29 chars
        
        print(f"{f} | Prefix OK: {has_prefix} | Overflow: {overflow_risk} | Longest Option: '{longest_text}' ({max_len} chars)")
