SEED_SCHEDULES = [
    {'section': 'BSCS 101 - A', 'course': 'COSC 50', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A2', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSCS 101 - A', 'course': 'CvSU 101', 'faculty': 'T.B.A.', 'room': 'A2', 'day': 'Monday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 101 - A', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'A1', 'day': 'Wednesday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 101 - A', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'B2', 'day': 'Wednesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 101 - A', 'course': 'DCIT 22', 'faculty': 'ALLEN JOHN C. MUYOT', 'room': 'B1', 'day': 'Monday', 'start': 7, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 101 - A', 'course': 'DCIT 22', 'faculty': 'ALLEN JOHN C. MUYOT', 'room': 'A1', 'day': 'Wednesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 101 - B', 'course': 'COSC 50', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A2', 'day': 'Monday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 101 - B', 'course': 'CvSU 101', 'faculty': 'T.B.A.', 'room': 'A3', 'day': 'Monday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 101 - B', 'course': 'DCIT 21', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'B2', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 101 - B', 'course': 'DCIT 21', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'A1', 'day': 'Monday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSCS 101 - B', 'course': 'DCIT 22', 'faculty': 'ALLEN JOHN C. MUYOT', 'room': 'A1', 'day': 'Monday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 101 - B', 'course': 'DCIT 22', 'faculty': 'ALLEN JOHN C. MUYOT', 'room': 'B1', 'day': 'Wednesday', 'start': 13, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 101 - C', 'course': 'COSC 50', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A2', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSCS 101 - C', 'course': 'CvSU 101', 'faculty': 'T.B.A.', 'room': 'A3', 'day': 'Monday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 101 - C', 'course': 'DCIT 21', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'A1', 'day': 'Monday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 101 - C', 'course': 'DCIT 21', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'B1', 'day': 'Wednesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 101 - C', 'course': 'DCIT 22', 'faculty': 'DCS Teacher E (CS)', 'room': 'B1', 'day': 'Friday', 'start': 7, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 101 - C', 'course': 'DCIT 22', 'faculty': 'DCS Teacher E (CS)', 'room': 'A1', 'day': 'Monday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 201 - A', 'course': 'COSC 55', 'faculty': 'DCS Teacher E (CS)', 'room': 'A1', 'day': 'Wednesday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 201 - A', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A3', 'day': 'Monday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSCS 201 - A', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B1', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - A', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'A3', 'day': 'Monday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 201 - A', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'B1', 'day': 'Wednesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - A', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A3', 'day': 'Monday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 201 - A', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'B1', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - A', 'course': 'INSY 50', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'A2', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSCS 201 - B', 'course': 'COSC 55', 'faculty': 'DCS Teacher E (CS)', 'room': 'A1', 'day': 'Wednesday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 201 - B', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A4', 'day': 'Monday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 201 - B', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B2', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - B', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'A2', 'day': 'Wednesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 201 - B', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'B2', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - B', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A4', 'day': 'Monday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSCS 201 - B', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'B2', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - B', 'course': 'INSY 50', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'A2', 'day': 'Wednesday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 201 - C', 'course': 'COSC 55', 'faculty': 'DCS Teacher E (CS)', 'room': 'A1', 'day': 'Friday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSCS 201 - C', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A2', 'day': 'Wednesday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 201 - C', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B3', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - C', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'B3', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - C', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'A3', 'day': 'Monday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSCS 201 - C', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A4', 'day': 'Monday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 201 - C', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'B2', 'day': 'Wednesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - C', 'course': 'INSY 50', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'A1', 'day': 'Friday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSCS 201 - D', 'course': 'COSC 55', 'faculty': 'DCS Teacher E (CS)', 'room': 'A4', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 201 - D', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A5', 'day': 'Monday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 201 - D', 'course': 'COSC 60', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B3', 'day': 'Wednesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - D', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'B1', 'day': 'Friday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - D', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'A4', 'day': 'Monday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 201 - D', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A3', 'day': 'Wednesday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 201 - D', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'B3', 'day': 'Wednesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 201 - D', 'course': 'INSY 50', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'A1', 'day': 'Friday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A1', 'day': 'Thursday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'B1', 'day': 'Thursday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'A1', 'day': 'Tuesday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'B1', 'day': 'Tuesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A1', 'day': 'Tuesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'B1', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 85', 'faculty': 'DCS Teacher H (JM) - IT', 'room': 'A1', 'day': 'Saturday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 301 - A', 'course': 'COSC 85', 'faculty': 'DCS Teacher H (JM) - IT', 'room': 'B1', 'day': 'Saturday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - A', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'A1', 'day': 'Thursday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 301 - A', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'B1', 'day': 'Thursday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - A', 'course': 'DCIT 65', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A1', 'day': 'Saturday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'B2', 'day': 'Thursday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A1', 'day': 'Tuesday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'B1', 'day': 'Thursday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'A1', 'day': 'Tuesday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'B1', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A1', 'day': 'Tuesday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 85', 'faculty': 'DCS Teacher H (JM) - IT', 'room': 'B1', 'day': 'Saturday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - B', 'course': 'COSC 85', 'faculty': 'DCS Teacher H (JM) - IT', 'room': 'A2', 'day': 'Tuesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 301 - B', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'B2', 'day': 'Thursday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - B', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'A1', 'day': 'Tuesday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 301 - B', 'course': 'DCIT 65', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A1', 'day': 'Saturday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A2', 'day': 'Tuesday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'B2', 'day': 'Tuesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'B2', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'A2', 'day': 'Tuesday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'B2', 'day': 'Thursday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A2', 'day': 'Tuesday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 85', 'faculty': 'IVAN TOLEDO', 'room': 'B1', 'day': 'Saturday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - C', 'course': 'COSC 85', 'faculty': 'IVAN TOLEDO', 'room': 'A1', 'day': 'Thursday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 301 - C', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'T.B.A.', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - C', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'A3', 'day': 'Tuesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 301 - C', 'course': 'DCIT 65', 'faculty': 'DCS Teacher F (CS)', 'room': 'A1', 'day': 'Thursday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'B3', 'day': 'Thursday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A3', 'day': 'Tuesday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'B3', 'day': 'Thursday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'A4', 'day': 'Tuesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'B3', 'day': 'Thursday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A2', 'day': 'Tuesday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 85', 'faculty': 'DCS Teacher G (DON) - IT', 'room': 'B2', 'day': 'Saturday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - D', 'course': 'COSC 85', 'faculty': 'DCS Teacher G (DON) - IT', 'room': 'A1', 'day': 'Saturday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 301 - D', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'B2', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - D', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'A2', 'day': 'Tuesday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSCS 301 - D', 'course': 'DCIT 65', 'faculty': 'DCS Teacher F (CS)', 'room': 'A2', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'T.B.A.', 'day': 'Monday', 'start': 15, 'end': 18, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 101', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A5', 'day': 'Tuesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'T.B.A.', 'day': 'Monday', 'start': 11, 'end': 14, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 75', 'faculty': 'ALYANA CABRIDO', 'room': 'A2', 'day': 'Thursday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'T.B.A.', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 80', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A2', 'day': 'Thursday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 85', 'faculty': 'DCS Teacher G (DON) - IT', 'room': 'B4', 'day': 'Thursday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - E', 'course': 'COSC 85', 'faculty': 'DCS Teacher G (DON) - IT', 'room': 'A3', 'day': 'Tuesday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSCS 301 - E', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'B3', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 301 - E', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'A4', 'day': 'Tuesday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 301 - E', 'course': 'DCIT 65', 'faculty': 'DCS Teacher F (CS)', 'room': 'A3', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 401 - A', 'course': 'COSC 100', 'faculty': 'DCS Teacher F (CS)', 'room': 'A5', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 401 - A', 'course': 'COSC 105', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A5', 'day': 'Monday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 401 - A', 'course': 'COSC 105', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'B2', 'day': 'Monday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSCS 401 - A', 'course': 'COSC 111', 'faculty': 'DCS Teacher E (CS)', 'room': 'A5', 'day': 'Monday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSCS 401 - A', 'course': 'COSC 111', 'faculty': 'DCS Teacher E (CS)', 'room': 'B4', 'day': 'Wednesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 401 - A', 'course': 'COSC 200A', 'faculty': 'CHRISTOPHER G. ESTONILO', 'room': 'A3', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSCS 401 - B', 'course': 'COSC 100', 'faculty': 'DCS Teacher F (CS)', 'room': 'A3', 'day': 'Wednesday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 401 - B', 'course': 'COSC 105', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'B3', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 401 - B', 'course': 'COSC 105', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A2', 'day': 'Wednesday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSCS 401 - B', 'course': 'COSC 111', 'faculty': 'DCS Teacher E (CS)', 'room': 'A5', 'day': 'Monday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSCS 401 - B', 'course': 'COSC 111', 'faculty': 'DCS Teacher E (CS)', 'room': 'B4', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSCS 401 - B', 'course': 'COSC 200A', 'faculty': 'KARLO JOSE E. NABABLIT', 'room': 'A1', 'day': 'Friday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 401 - C', 'course': 'COSC 100', 'faculty': 'DCS Teacher F (CS)', 'room': 'A4', 'day': 'Wednesday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSCS 401 - C', 'course': 'COSC 105', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'B3', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSCS 401 - C', 'course': 'COSC 105', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A3', 'day': 'Wednesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSCS 401 - C', 'course': 'COSC 111', 'faculty': 'DCS Teacher E (CS)', 'room': 'A2', 'day': 'Friday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSCS 401 - C', 'course': 'COSC 111', 'faculty': 'DCS Teacher E (CS)', 'room': 'T.B.A.', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSCS 401 - C', 'course': 'COSC 200A', 'faculty': 'MARY ANN E. IGNACO', 'room': 'A4', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSHM 201 - A', 'course': 'BSHM 23', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'HM-A1', 'day': 'Monday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSHM 201 - A', 'course': 'BSHM 23', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'HM-Lab', 'day': 'Monday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSHM 201 - B', 'course': 'BSHM 23', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'HM-A1', 'day': 'Monday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSHM 201 - B', 'course': 'BSHM 23', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'HM-Lab', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSHM 201 - C', 'course': 'BSHM 23', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'HM-A1', 'day': 'Wednesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSHM 201 - C', 'course': 'BSHM 23', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'HM-Lab', 'day': 'Wednesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSHM 201 - D', 'course': 'BSHM 23', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'HM-A1', 'day': 'Tuesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSHM 201 - D', 'course': 'BSHM 23', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'HM-Lab', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSHM 201 - E', 'course': 'BSHM 23', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'HM-A1', 'day': 'Tuesday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSHM 201 - E', 'course': 'BSHM 23', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'HM-Lab', 'day': 'Tuesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSHM 201 - F', 'course': 'BSHM 23', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'HM-A1', 'day': 'Thursday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSHM 201 - F', 'course': 'BSHM 23', 'faculty': 'GIRLIE P. MELITANTE', 'room': 'HM-Lab', 'day': 'Thursday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 101 - A', 'course': 'COSC 50', 'faculty': 'RACQUEL A. CATALAN', 'room': 'A5', 'day': 'Tuesday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - A', 'course': 'CvSU 101', 'faculty': 'T.B.A.', 'room': 'A2', 'day': 'Thursday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - A', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'B5', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 101 - A', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'A4', 'day': 'Tuesday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - A', 'course': 'DCIT 22', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A1', 'day': 'Thursday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - A', 'course': 'DCIT 22', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'B3', 'day': 'Tuesday', 'start': 7, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 101 - B', 'course': 'COSC 50', 'faculty': 'RACQUEL A. CATALAN', 'room': 'A4', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - B', 'course': 'CvSU 101', 'faculty': 'T.B.A.', 'room': 'A3', 'day': 'Thursday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - B', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'A2', 'day': 'Thursday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - B', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'B1', 'day': 'Tuesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 101 - B', 'course': 'DCIT 22', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'B4', 'day': 'Thursday', 'start': 7, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 101 - B', 'course': 'DCIT 22', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A3', 'day': 'Tuesday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - C', 'course': 'COSC 50', 'faculty': 'RACQUEL A. CATALAN', 'room': 'A3', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - C', 'course': 'CvSU 101', 'faculty': 'T.B.A.', 'room': 'A5', 'day': 'Tuesday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - C', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'B5', 'day': 'Thursday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 101 - C', 'course': 'DCIT 21', 'faculty': 'MARY GRACE P. SILVANO', 'room': 'A5', 'day': 'Tuesday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 101 - C', 'course': 'DCIT 22', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'B2', 'day': 'Saturday', 'start': 13, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 101 - C', 'course': 'DCIT 22', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A4', 'day': 'Tuesday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 201 - A', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'A3', 'day': 'Thursday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 201 - A', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'B2', 'day': 'Tuesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 201 - A', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'B1', 'day': 'Tuesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 201 - A', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A5', 'day': 'Tuesday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 201 - B', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'A3', 'day': 'Thursday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 201 - B', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'B2', 'day': 'Tuesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 201 - B', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A3', 'day': 'Thursday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 201 - B', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'B4', 'day': 'Tuesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 201 - C', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'A4', 'day': 'Thursday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 201 - C', 'course': 'DCIT 24', 'faculty': 'ANGELA C. CLARITO', 'room': 'B3', 'day': 'Tuesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 201 - C', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A4', 'day': 'Thursday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 201 - C', 'course': 'DCIT 50', 'faculty': 'RENATO A. BAUTISTA', 'room': 'B4', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 202 - A', 'course': 'ITEC 55', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'B3', 'day': 'Monday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 202 - A', 'course': 'ITEC 55', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A3', 'day': 'Wednesday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 202 - B', 'course': 'ITEC 55', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'B4', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 202 - B', 'course': 'ITEC 55', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A4', 'day': 'Wednesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 202 - C', 'course': 'ITEC 55', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'B5', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 202 - C', 'course': 'ITEC 55', 'faculty': 'JANESSA MARIELLE S. CRUZ', 'room': 'A4', 'day': 'Wednesday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'A2', 'day': 'Saturday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'B1', 'day': 'Saturday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'DCIT 60', 'faculty': 'KARLO JOSE E. NABABLIT', 'room': 'A5', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'DCIT 65', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A2', 'day': 'Saturday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'INSY 55', 'faculty': 'YVANA JARDINE R. NOCON', 'room': 'A4', 'day': 'Thursday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'INSY 55', 'faculty': 'YVANA JARDINE R. NOCON', 'room': 'B5', 'day': 'Tuesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'A4', 'day': 'Thursday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'B3', 'day': 'Tuesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A4', 'day': 'Thursday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B4', 'day': 'Tuesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'ITEC 90', 'faculty': 'LESTER D. VILLANUEVA', 'room': 'A4', 'day': 'Thursday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - A', 'course': 'ITEC 90', 'faculty': 'LESTER D. VILLANUEVA', 'room': 'B5', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'B2', 'day': 'Saturday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'A2', 'day': 'Saturday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'DCIT 60', 'faculty': 'ARIES M. GELERA', 'room': 'A2', 'day': 'Saturday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'DCIT 65', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'A3', 'day': 'Saturday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'INSY 55', 'faculty': 'YVANA JARDINE R. NOCON', 'room': 'A5', 'day': 'Thursday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'INSY 55', 'faculty': 'YVANA JARDINE R. NOCON', 'room': 'B6', 'day': 'Tuesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'A5', 'day': 'Thursday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'B5', 'day': 'Tuesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A5', 'day': 'Thursday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B4', 'day': 'Tuesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'ITEC 90', 'faculty': 'LESTER D. VILLANUEVA', 'room': 'A5', 'day': 'Thursday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - B', 'course': 'ITEC 90', 'faculty': 'LESTER D. VILLANUEVA', 'room': 'B6', 'day': 'Tuesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'T.B.A.', 'day': 'Monday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'DCIT 26', 'faculty': 'AARON TINAMBACAN', 'room': 'T.B.A.', 'day': 'Monday', 'start': 9, 'end': 12, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'DCIT 60', 'faculty': 'CHRISTOPHER G. ESTONILO', 'room': 'A4', 'day': 'Saturday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'DCIT 65', 'faculty': 'JOHN CHRISTIAN PERNALA', 'room': 'T.B.A.', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'INSY 55', 'faculty': 'YVANA JARDINE R. NOCON', 'room': 'A3', 'day': 'Saturday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'INSY 55', 'faculty': 'YVANA JARDINE R. NOCON', 'room': 'B5', 'day': 'Tuesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'A3', 'day': 'Saturday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'B4', 'day': 'Thursday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A3', 'day': 'Saturday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B6', 'day': 'Thursday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'ITEC 90', 'faculty': 'LESTER D. VILLANUEVA', 'room': 'A3', 'day': 'Saturday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - C', 'course': 'ITEC 90', 'faculty': 'LESTER D. VILLANUEVA', 'room': 'B6', 'day': 'Tuesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'DCIT 26', 'faculty': 'DCS Teacher F (CS)', 'room': 'B5', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'DCIT 26', 'faculty': 'DCS Teacher F (CS)', 'room': 'A5', 'day': 'Wednesday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'DCIT 60', 'faculty': 'MARY ANN E. IGNACO', 'room': 'A2', 'day': 'Friday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'INSY 55', 'faculty': 'ANA MARIE C. OBON', 'room': 'B4', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'INSY 55', 'faculty': 'ANA MARIE C. OBON', 'room': 'A5', 'day': 'Wednesday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'B4', 'day': 'Monday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'A5', 'day': 'Wednesday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'B1', 'day': 'Friday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'ITEC 85', 'faculty': 'VHINCE LORENZ DELA REA', 'room': 'A5', 'day': 'Wednesday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'ITEC 90', 'faculty': 'KARL VINCENT M. ORDOÑA', 'room': 'B4', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - D', 'course': 'ITEC 90', 'faculty': 'KARL VINCENT M. ORDOÑA', 'room': 'A5', 'day': 'Wednesday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'DCIT 26', 'faculty': 'DCS Teacher F (CS)', 'room': 'A3', 'day': 'Friday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'DCIT 26', 'faculty': 'DCS Teacher F (CS)', 'room': 'B5', 'day': 'Wednesday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'DCIT 60', 'faculty': 'MARY ANN E. IGNACO', 'room': 'T.B.A.', 'day': 'Tuesday', 'start': 7, 'end': 10, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'INSY 55', 'faculty': 'ANA MARIE C. OBON', 'room': 'A2', 'day': 'Friday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'INSY 55', 'faculty': 'ANA MARIE C. OBON', 'room': 'B5', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'B5', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'ITEC 80', 'faculty': 'CEDRICK KENN CEDILLO', 'room': 'A5', 'day': 'Wednesday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'ITEC 85', 'faculty': 'IVAN TOLEDO', 'room': 'A2', 'day': 'Friday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'ITEC 85', 'faculty': 'IVAN TOLEDO', 'room': 'B5', 'day': 'Monday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'ITEC 90', 'faculty': 'KARL VINCENT M. ORDOÑA', 'room': 'A2', 'day': 'Friday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 301 - E', 'course': 'ITEC 90', 'faculty': 'KARL VINCENT M. ORDOÑA', 'room': 'B6', 'day': 'Monday', 'start': 7, 'end': 10, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - A', 'course': 'ITEC 110', 'faculty': 'ALYANA CABRIDO', 'room': 'A3', 'day': 'Friday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - A', 'course': 'ITEC 110', 'faculty': 'ALYANA CABRIDO', 'room': 'B6', 'day': 'Monday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - A', 'course': 'ITEC 111', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A3', 'day': 'Friday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - A', 'course': 'ITEC 111', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'B6', 'day': 'Monday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - A', 'course': 'ITEC 116', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A3', 'day': 'Friday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - A', 'course': 'ITEC 116', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'B4', 'day': 'Wednesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - A', 'course': 'ITEC 200B', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A3', 'day': 'Friday', 'start': 16, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - B', 'course': 'ITEC 110', 'faculty': 'ALYANA CABRIDO', 'room': 'A4', 'day': 'Friday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - B', 'course': 'ITEC 110', 'faculty': 'ALYANA CABRIDO', 'room': 'B2', 'day': 'Wednesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - B', 'course': 'ITEC 111', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A4', 'day': 'Friday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - B', 'course': 'ITEC 111', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'B6', 'day': 'Monday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - B', 'course': 'ITEC 116', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A4', 'day': 'Friday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - B', 'course': 'ITEC 116', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'B6', 'day': 'Wednesday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - B', 'course': 'ITEC 200B', 'faculty': 'RENATO A. BAUTISTA', 'room': 'A4', 'day': 'Friday', 'start': 13, 'end': 16, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - C', 'course': 'ITEC 110', 'faculty': 'ALYANA CABRIDO', 'room': 'A5', 'day': 'Friday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - C', 'course': 'ITEC 110', 'faculty': 'ALYANA CABRIDO', 'room': 'B5', 'day': 'Wednesday', 'start': 16, 'end': 19, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - C', 'course': 'ITEC 111', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'A4', 'day': 'Friday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - C', 'course': 'ITEC 111', 'faculty': 'IAN CHRISTOPHER ADAL', 'room': 'B3', 'day': 'Wednesday', 'start': 10, 'end': 13, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - C', 'course': 'ITEC 116', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'A5', 'day': 'Friday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BSINFOTECH 401 - C', 'course': 'ITEC 116', 'faculty': 'KYLE ANGELO AMBIL', 'room': 'B2', 'day': 'Friday', 'start': 13, 'end': 16, 'type': 'Laboratory'},
    {'section': 'BSINFOTECH 401 - C', 'course': 'ITEC 200B', 'faculty': 'ARIES M. GELERA', 'room': 'A4', 'day': 'Saturday', 'start': 10, 'end': 13, 'type': 'Lecture'},
    {'section': 'BTVTED 301 - A', 'course': 'TLEP 08', 'faculty': 'ANA MARIE C. OBON', 'room': 'A1', 'day': 'Monday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'BTVTED 301 - B', 'course': 'TLEP 08', 'faculty': 'ANA MARIE C. OBON', 'room': 'A1', 'day': 'Monday', 'start': 9, 'end': 11, 'type': 'Lecture'},
    {'section': 'Grade 10', 'course': 'TLE 4', 'faculty': 'T.B.A.', 'room': 'K-12 Room', 'day': 'Saturday', 'start': 11, 'end': 13, 'type': 'Lecture'},
    {'section': 'Grade 10', 'course': 'TLE 4', 'faculty': 'T.B.A.', 'room': 'K-12 Room', 'day': 'Saturday', 'start': 13, 'end': 15, 'type': 'Lecture'},
    {'section': 'Grade 11', 'course': 'ICT 11', 'faculty': 'T.B.A.', 'room': 'K-12 Room', 'day': 'Saturday', 'start': 15, 'end': 17, 'type': 'Lecture'},
    {'section': 'Grade 11', 'course': 'ICT 11', 'faculty': 'T.B.A.', 'room': 'K-12 Room', 'day': 'Saturday', 'start': 17, 'end': 19, 'type': 'Lecture'},
    {'section': 'Grade 9', 'course': 'TLE 3', 'faculty': 'T.B.A.', 'room': 'K-12 Room', 'day': 'Saturday', 'start': 7, 'end': 9, 'type': 'Lecture'},
    {'section': 'Grade 9', 'course': 'TLE 3', 'faculty': 'T.B.A.', 'room': 'K-12 Room', 'day': 'Saturday', 'start': 9, 'end': 11, 'type': 'Lecture'},
]
# Total: 258 sessions